# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

matrix:
  include:
    - dist: xenial
      python: 3.5
      env: TOXENV="py35"
    - dist: xenial
      python: 3.6
      env: TOXENV="py36"
    - dist: xenial
      python: 3.7
      env: TOXENV="py37,doit,codecov"
    - os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell
      env: TOXENV="py37"
      before_install: python3 --version
    - os: windows
      language: shell
      before_install: choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
          TOXENV="py37"


install:
  - pip3 install tox

script:
  - tox
