# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: required
dist: trusty

language: python

matrix:
  include:
    - os: linux
      python: "3.5"
      env: TOXENV="py35"
    - os: linux
      python: "3.6"
      env: TOXENV="py36"
    - os: linux
      python: "3.7-dev"
      env: TOXENV="py37,doit,codecov"
    - os: osx
      language: generic
      env: TOXENV="py37"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install enchant; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 --version; fi

install:
  - python3 -m pip install tox

script:
  - python3 -m tox
